spring.application.name=BackendPiedraAzul
server.port=8081
# KEYCLOAK
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/piedraAzul-dev
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/piedraAzul-dev/protocol/openid-connect/certs

jwt.auth.converter.principle-attribute=preferred_username
jwt.auth.converter.resource-id=piedraAzul-dev

logging.level.org.keycloak=DEBUG
debug=true

# H2 DATABASE
spring.datasource.url=jdbc:h2:file:./data/projectDb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=none

# H2 CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console