spring.application.name=BackendPiedraAzul
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT:8081}

# KEYCLOAK
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/piedraAzul-dev}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/piedraAzul-dev/protocol/openid-connect/certs}

jwt.auth.converter.principle-attribute=${JWT_PRINCIPLE_ATTRIBUTE:preferred_username}
jwt.auth.converter.resource-id=${KEYCLOAK_RESOURCE_ID:piedraAzul-dev}

keycloak.admin.server-url=${KEYCLOAK_ADMIN_SERVER_URL:http://localhost:8080}
keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:piedraAzul-dev}
keycloak.admin.master-realm=${KEYCLOAK_ADMIN_MASTER_REALM:master}
keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:1234}
keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:HFn9D3q4cLaZyLfTcs7h4J4cDLLLaRLh}

keycloak.token-url=${KEYCLOAK_TOKEN_URL:http://localhost:8080/realms/piedraAzul-dev/protocol/openid-connect/token}
keycloak.client-id=${KEYCLOAK_CLIENT_ID:piedraAzul-app}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET:}
keycloak.test.username=${KEYCLOAK_TEST_USERNAME:macarela}
keycloak.test.password=${KEYCLOAK_TEST_PASSWORD:1234}
backend.test.login-url=${BACKEND_LOGIN_TEST_URL:http://localhost:8081/test/login-test}

# AUTH COOKIES
auth.cookie.access-name=${AUTH_COOKIE_ACCESS_NAME:PA_ACCESS}
auth.cookie.refresh-name=${AUTH_COOKIE_REFRESH_NAME:PA_REFRESH}
auth.cookie.same-site=${AUTH_COOKIE_SAME_SITE:Lax}
auth.cookie.secure=${AUTH_COOKIE_SECURE:false}
auth.cookie.path=${AUTH_COOKIE_PATH:/}
auth.cookie.domain=${AUTH_COOKIE_DOMAIN:}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:4300}

# POSTGRESQL DATABASE
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/piedraazul}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:paco}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# WHATSAPP
twilio.account-sid=${TWILIO_ACCOUNT_SID:}
twilio.auth-token=${TWILIO_AUTH_TOKEN:}
twilio.whatsapp-from=${TWILIO_WHATSAPP_FROM:}