name: cd

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to local machine
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        shell: powershell
        run: |
          & "$env:GITHUB_WORKSPACE\deploy.ps1"
